language: cpp
compiler: clang

before_script:
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz -O /tmp/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -xvf /tmp/cmake-3.2.3-Linux-x86_64.tar.gz
  - export PATH=$PWD/cmake-3.2.3-Linux-x86_64/bin:$PATH
  - sudo apt-get install -y opencl-headers
  - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_7.0-28_amd64.deb
  - sudo dpkg -i cuda-repo-ubuntu1204_7.0-28_amd64.deb
  - sudo apt-get update -qq
  - sudo apt-get install -y cuda
  - export PATH=/usr/local/cuda-7.0/bin:$PATH 
  - export LD_LIBRARY_PATH=/usr/local/cuda-7.0/lib64:$LD_LIBRARY_PATH
  - export CUDA_PATH=/usr/local/cuda-7.0
  - mkdir build
  - cd build
  - cmake ..

script: make
